version: "3.8"

services:
  postgresql:
    image: postgres:15.2
    container_name: postgres_rec_session
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234567
      POSTGRES_USER: admin
      POSTGRES_DB: rec_session
      PGDATA: /data
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "54322:5432"